name: pub_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  auto_size_text: ^3.0.0
  clickup_fading_scroll:
    git:
      url: https://github.com/clickup/clickup_fading_scroll.git
  copy_with_extension: ^4.0.3
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  flutter_html_all: ^3.0.0-alpha.5
  flutter_riverpod: ^2.0.0-dev.9
  google_fonts: ^3.0.1
  isar: ^3.0.0-dev.13
  isar_flutter_libs: ^3.0.0-dev.13
  json_annotation: ^4.6.0
  markdown: ^6.0.0
  pub_semver: ^2.1.1
  pubspec: ^2.3.0
  pubspec_parse: ^1.2.1
  riverpod: ^2.0.0-dev.9
  shimmer: ^2.0.0
  tar: ^0.5.6
  timeago: ^3.3.0
  url_launcher: ^6.1.5

dev_dependencies:
  build_runner: ^2.0.0
  copy_with_extension_gen: ^4.0.3
  go_router: ^4.3.0
  isar_generator: ^3.0.0-dev.13
  json_serializable: ^6.3.0
  very_good_analysis: ^3.0.1

dependency_overrides:
  isar: 
    path: ../../packages/isar
  isar_generator: 
    path: ../../packages/isar_generator
  isar_flutter_libs: ^3.0.0-dev.13

flutter:
  uses-material-design: true
  assets:
    - assets/ff_banner.png
    - assets/pub_logo.svg
    - assets/pub_logo_dark.svg
    - assets/search_bg.svg