name: isar_annotation
description: Isar database annotations
version: 0.0.1-nullsafety.0

repository: https://github.com/isar/isar

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
