name: isar_annotation
description: Isar Database annotations to automatically generate schema.
version: 0.0.3

repository: https://github.com/isar/isar

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
