name: isar_generator
description: Code generator for the Isar Database. Finds classes annotated with @IsarCollection.
version: 2.0.0
repository: https://github.com/isar/isar
homepage: https://isar.dev

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  isar: 2.0.0
  build: ^2.1.0
  source_gen: ^1.0.5
  analyzer: ^3.0.0
  glob: ^2.0.1
  path: ^1.8.0
  dart_style: ^2.0.3
  json_annotation: ^4.3.0
  dartx: ^1.0.0
  freezed_annotation: ^1.1.0

dev_dependencies:
  json_serializable: ^6.1.0
  build_runner: ^2.1.1
  freezed: ^1.1.0
  lints: ^1.0.1
