name: isar
description: Fast Cross Platform Database for Flutter Apps. Supports indexes, FTS, queries etc.
version: 3.0.0-dev.2
repository: https://github.com/isar/isar
homepage: https://isar.dev

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  ffi: ^1.2.1
  js: ^0.6.4
  meta: ^1.7.0

dev_dependencies:
  ffigen: ^5.0.0
  test: ^1.21.1
  very_good_analysis: ^3.0.1
