name: isar_connect
description: Use this package to connect your app to the Isar Inspector.
version: 0.4.0
repository: https://github.com/isar/isar
homepage: https://isar.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  isar: 0.4.0
  pedantic: ^1.9.0

dependency_overrides:
  isar: 
    path: ../isar
