name: isar_connect
description: Use this package to connect your app to the Isar Inspector.
version: 2.0.0-dev.0
repository: https://github.com/isar/isar
homepage: https://isar.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  isar: 2.0.0-dev.0

dev_dependencies:
  lints: ^1.0.1
