name: isar_connect
description: Use this package to connect your app to the Isar Inspector.
version: 1.0.5
repository: https://github.com/isar/isar
homepage: https://isar.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  isar: ">=1.0.0 <1.1.0"

dev_dependencies:
  lints: ^1.0.1
