name: root_package

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  isar: any
  isar_test:
    path: ../../isar_test
  child_package1:
    path: ../child_package1
  child_package2:
    path: ../child_package2

dev_dependencies:
  build_runner: any
  isar_generator: any
  freezed: any
  test: ^1.17.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  isar:
    path: ../../isar
  isar_flutter_libs:
    path: ../../isar_flutter_libs
  isar_generator:
    path: ../../isar_generator
