name: root_package

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  isar: any
  child_package1:
    path: ../child_package1
  child_package2:
    path: ../child_package2

dev_dependencies:
  test: any
  isar_generator: any
  build_runner: any
  isar_test:
    path: ../../isar_test

dependency_overrides:
  isar:
    path: ../../isar
  isar_generator:
    path: ../../isar_generator
  crypto: ^3.0.0
  convert: ^3.0.0
