name: isar_inspector
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dartx: ^1.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0-dev.7
  flutter_svg: any
  font_awesome_flutter: any
  go_router: ^4.1.0
  google_fonts: ^3.0.1
  isar: any
  json_annotation: ^4.5.0
  petitparser: ^4.4.0
  vm_service: ^9.0.0
  web_socket_channel: ^2.2.0
  

dev_dependencies:
  build_runner: any
  flutter_lints: ^2.0.1
  json_serializable: ^6.2.0
  very_good_analysis: ^3.0.1

dependency_overrides:
  isar:
    path: ../isar

flutter:
  uses-material-design: true

  assets:
    - assets/logo.svg
