name: isar
description: Isar databases

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  isar_annotation: 0.0.1-nullsafety.0
  ffi: 0.2.0-nullsafety.1
  path:

dev_dependencies:
  pedantic: ^1.9.0
  isar_generator: any
  build_runner: any
  ffigen: any
  test: 1.16.0-nullsafety.13

dependency_overrides:
  isar_annotation:
    path: ../isar_annotation
  isar_generator:
    path: ../isar_generator
  ffi: 0.2.0-nullsafety.1