name: isar
description: Isar databases

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  isar_annotation: 0.0.1-nullsafety.0
  ffi: 0.2.0-nullsafety.1
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.9.0
  #ffigen: any

dependecy_overrides:
  isar_annotation:
    path: ../isar_annotation