name: isar
description: Fast Cross Platform Database for Flutter & Web Apps. Supports indexes, FTS, queries etc.
version: 0.1.0
repository: https://github.com/isar/isar
homepage: https://isar.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  isar_annotation: 0.1.0
  ffi: ^1.0.0
  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.16.0
  ffigen: ^2.2.5
  meta: any