name: Dart CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
        working-directory: isar_test

      - name: Run isar_generator
        run: flutter pub run build_runner build
        working-directory: isar_test
        
      - name: Download binaries
        run: bash tool/setup_tests.sh
        working-directory: isar_test
      
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      
      - name: Run tests
        run: flutter test
        working-directory: isar_test
