name: Dart CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image:  google/dart:beta

    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: dart pub get
        working-directory: isar

      - name: Run isar_generator
        run: dart run build_runner build
        working-directory: isar
        
      - name: Download binaries
        run: bash tool/setup_tests.sh
        working-directory: isar
        
      - name: Run tests
        run: dart test
        working-directory: isar
